### ISSUE TITLE
Photosphere

### ISSUE THREAD

**Issue by Buuhuu** [hlxsites/vg-volvotrucks-us#196]
https://www.volvotrucks.us/trucks/vhd/interior/

There is a moveable photo sphere on the vhd interior page. The library used seems to be https://photo-sphere-viewer.js.org/guide/#your-first-viewer

<img width="1999" alt="Screenshot 2023-04-04 at 08 00 38" src="https://user-images.githubusercontent.com/558094/229701182-726c7595-4408-4a2b-a561-6f997770de9f.png">

**Comment by girishdigrajkar** [comment]
Validated on https://main--vg-volvotrucks-us--hlxsites.hlx.live/trucks/vhd/interior/ and able to zoom in/out and see 360 scroll on desktop browser.

On the mobile viewport we are able to zoom in /out successfully however, due to limitation that we cannot use finger touch for 360 navigation thus, this is not testable with current setup. 

Above limitation to be tested on live. @Joesturbo : please approve this approach.    cc: @verareljic @manuel-vara @Andrei-Boiangiu
