### ISSUE TITLE
Videos in Teaser Grid are not shown

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-volvotrucks-us#386]
the videos on https://www.volvotrucks.us/our-difference/uptime-and-connectivity/ are not shown.

![image](https://user-images.githubusercontent.com/2250964/234054058-886bf328-bbda-4af3-90fa-d4bd0fa46806.png)

**Comment by jonatan-lledo-netcentric** [comment]
<img width="525" alt="Screenshot 2023-04-25 at 10 32 27" src="https://user-images.githubusercontent.com/117984204/234221202-b6577c38-3c32-4da1-a16c-cb0bcd27b4d7.png">
<img width="525" alt="Screenshot 2023-04-25 at 10 37 45" src="https://user-images.githubusercontent.com/117984204/234222256-113b5d4d-ea0d-4532-b2b5-266231be8fa8.png">

it seems a cookie config issue because I tested in incognito mode and the 5th cookie options are present

**Comment by synox** [comment]
I only see two options
<img width="527" alt="Screenshot 2023-04-28 at 07 50 56" src="https://user-images.githubusercontent.com/2250964/235180636-9a6f19e0-0fed-4d8c-9b8b-f385b2d38c89.png">

**Comment by synox** [comment]
I did now reset my cookies, and now it works.
