### ISSUE TITLE
block: magazine article list

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/vg-volvotrucks-us#54]
https://www.volvotrucks.us/news-and-stories/
https://www.volvotrucks.us/news-and-stories/volvo-trucks-magazine/

https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/

Ideally this block would be flexible/configurable to handle both views

**Comment by dkuntze** [comment]
article feed coming from the query index for magazine

**Comment by Buuhuu** [comment]
@dkuntze on https://www.volvotrucks.us/news-and-stories/ do you refer to the "Press Releases" teasers? If so that looks more like Teaser Cards block backed by an index (reuse should be possible)

A list of pages, filtered by some criteria is also on https://www.volvotrucks.us/news-and-stories/press-releases/. 

So the block should support fulltext search (optional) and tag filters (optional, multiple).
