### ISSUE TITLE
FR: [V2 Stories Carousel] Variant - Related Articles 

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#541]
### Description
As a content author, I want to add a 'Related Articles' component to individual articles, improving user retention and engagement by offering relevant content suggestions, increasing page views, and enhancing overall user experience.

### Acceptance Criteria

- [ ] A block variant from "V2 stories carousel" will be developed that shows articles related to the current magazine article. 
- [ ] This block can be added to the [#560  - Template: Magazine Article](https://github.com/hlxsites/vg-volvotrucks-us/issues/560).
- [ ] The related articles should display the most recently published articles that have the same category tag. 
- [ ] If there are no similar article category tags, then the block should display the most recently published magazine articles. 
- [ ] The minimum articles displayed is three. If there are less than three related articles the next articles should be the most recently published. 
- [ ] The maximum limit of articles displayed is 7. 

### Attachments/Figma Links

**Desktop/Tablet:** https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1621%3A26647&mode=dev

**Mobile:** https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1602%3A25712&mode=dev

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/8e6b0862-89ed-411b-8aac-b5d082b8e960)

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/f35c148c-a8cf-459f-9464-6c9a23c97d94)

**Comment by ZoeBeykirch** [comment]
Removing dependency label now that https://github.com/hlxsites/vg-volvotrucks-us/issues/545 has been delivered.

**Comment by cincplug** [comment]
The related-articles variant for stories carousel was added to https://develop--vg-volvotrucks-us--hlxsites.aem.page/drafts/luka/driving-the-future/ where it appears above newsletter subscription.

It looks the same as the original stories one, but it filters article selection by tags. As agreed with @ZoeBeykirch: if the limit is 7, it will first show 7 articles matching the first tag of the currently open article. If there are less such articles than the limit, articles with second tag will be added and so on.

In order to test it with any other v2-magazine article page, please add the block in the same manner like for the above draft page. It should contain related-articles variant in table heading and optionally the overriding limit in second table row

**Comment by AsmitKMishra** [comment]
Testing Completed. Feature works as expected.
